# Generated by Django 4.1.3 on 2022-11-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_title', models.CharField(max_length=100)),
                ('vehicle_overview', models.TextField()),
                ('price_per_day', models.IntegerField()),
                ('model_year', models.CharField(max_length=4)),
                ('seating_capacity', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='default-banner.jpg', upload_to='media_pics/')),
                ('air_conditioner', models.BooleanField(default=False)),
                ('power_door_locks', models.BooleanField(default=False)),
                ('antilock_braking_system', models.BooleanField(default=False)),
                ('brake_assist', models.BooleanField(default=False)),
                ('power_steering', models.BooleanField(default=False)),
                ('driver_airbag', models.BooleanField(default=False)),
                ('passenger_airbag', models.BooleanField(default=False)),
                ('power_windows', models.BooleanField(default=False)),
                ('cd_player', models.BooleanField(default=False)),
                ('central_locking', models.BooleanField(default=False)),
                ('crash_sensor', models.BooleanField(default=False)),
                ('leather_seats', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField()),
                ('updation_date', models.DateField(auto_now_add=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fueltype')),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brands')),
            ],
        ),
    ]
